# Generated by Django 4.1 on 2022-08-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('sub_category', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('product_descpt', models.CharField(max_length=500)),
                ('creation_date', models.DateField()),
                ('image', models.ImageField(upload_to='shop/image')),
            ],
        ),
    ]
